linux-automation/usbsdmux

- usbsdmux/pca9536.py
Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>
> pca9536: fix typo in unused code path

- README.rst
Could ease people (especially those not that familiar with python) doing their first steps with usbsdmux.
Also simplified rst inline code markup to a more readable variant.
> Extend README.rst with a quickstart guide

- usbsdmux/__main__.py
Calling usbsdmux in direct mode with argument 'host' causes an error:
Traceback (most recent call last):
File "venv/bin/usbsdmux", line 10, in <module>
sys.exit(main())
File "/home/ejo/Code/usbsdmux/venv/lib/python3.5/site-packages/usbsdmux-0.1.4-py3.5.egg/usbsdmux/__main__.py", line 69, in main
File "/home/ejo/Code/usbsdmux/venv/lib/python3.5/site-packages/usbsdmux-0.1.4-py3.5.egg/usbsdmux/__main__.py", line 15, in direct_mode
NameError: name 'args' is not defined
The variable 'args' of main function is not accessible from function
'direct_mode', but we have the mode passed as parameter anyway and can
use this instead.
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>
> usbsdmux: fix invalid call of 'args' variable in conditional

- usbsdmux/usb2642i2c.py
The struct sg_io_hdr has a different size depending on the platform.
This adds a test case for armv7l.
A better way may be to check against the pointer size of platform but i
can not test this atm.
> Fixing size check of sgio for armv7

- README.rst
The systemd.unit manpage[1] lists `/etc/systemd/system` as the directory for
`"System units created by the administrator"`. The current `/etc/lib/systemd/system`
is probably a typo. Fix this.
[1]: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
> README: correct path for admin-created services

- usbsdmux/usbsdmux.py
Only sleep one second until the voltage-supply of the SD card is ~0 if `wait=True` is given.
Fixes: 3f9f04a ("High Level Application to control the usb-sd-mux from the command line")
> usbsdmux: honor wait argument in mode_disconnect()

- usbsdmux/usbsdmux.py
The previous implementation of this function did not correctly report
the off-state. Even if the device itself was off this function reported
the USB-SD-Mux to be in "dut-mode".
With this change the actual preference in hardware is respected.
In hardware the PWR_disable and DAT_disable signal has priority over the
switch-state selection.
Thus we need to check the disable-bit first. Only if disable is not set
we can be in dut- or host-mode.
Signed-off-by: Chris Fiege <cfi@pengutronix.de>
> commandline: 'get' must respect hardware signal priority

- usbsdmux/__main__.py
- usbsdmux/usb2642i2c.py
This PR fixes a bug in which a file is created in ``/dev/`` instead of a device node when the ``usbsdmux``-tool is called as root with a non-existing ``/dev/sg*`` parameter.
And while I was on it i also improved the error handling in the CLI. With this change the CLI only print the error message if a well-known Exception occurs.
> Do not create if device node does not exist

- .github/workflows/black.yml
- .github/workflows/flake8.yml
- .gitignore
- Makefile
- REQUIREMENTS.qa.txt
- fastentrypoints.py
- pyproject.toml
- setup.py
- usbsdmux/__main__.py
- usbsdmux/ctypehelper.py
- usbsdmux/pca9536.py
- usbsdmux/service.py
- usbsdmux/usb2642eeprom.py
- usbsdmux/usb2642i2c.py
- usbsdmux/usbsdmux.py
This PR adds `flake8` and `black` to this project.
We first set the tooling up for local use. Running `make qa` will run both tools and output any problems found.
Next:
* The code is reformatted using `black` and some odd whitespaces removed (while we are on it).
* Findings by `flake8` are corrected and the imports re-sorted.
Finally this PR adds Github actions to run the tools on push and in PRs.
> `flake8` and `black`: Fix Problems and add Actions for verification

- .gitignore
- usbsdmux/__main__.py
- usbsdmux/i2c_gpio.py
- usbsdmux/usb2642i2c.py
- usbsdmux/usbsdmux.py
The USB-SD-Mux FAST is a next generation prototype of the USB-SD-Mux.
This new generation contains  a new *I2C GPIO expander* and also provides two external open-drain outputs.
This PR adds support for this new hardware to this tooling.
For co-existence of old and new USB-SD-Muxes this PR also adds support to automatically detect the version of the USB-SD-Mux. This feature will also help to catch cases where the tooling is accidentally used on a another SCSI device (e.g. a hard drive or generic card reader).
> Add support for the USB-SD-Mux FAST

- usbsdmux/__main__.py
This fixes the typo mentioned in #59:
Closes #59
To be merged after #60.
> main: Fix Typo: It is ``a USB-SD-Mux``

- .github/workflows/pytest.yml
- tests/reference/02544d53413034471027b7748500bc00.json
- tests/reference/02544d53413034471027b7748500bc00.text
- tests/reference/1b534d474638533530d8466363a16700.json
- tests/reference/1b534d474638533530d8466363a16700.text
- tests/reference/744a605553442020104182bbc7010600.json
- tests/reference/744a605553442020104182bbc7010600.text
- tests/reference/9f5449303030303000a1114bb5011400.json
- tests/reference/9f5449303030303000a1114bb5011400.text
- tests/reference/regenerate.sh
- tests/test_sd_regs.py
> Add pytest tests and  a GitHub Actions workflow for SD register decoding

- .github/workflows/pytest.yml
- README.rst
- tests/test_cli.py
The usbsdmux -h output in the README.rst has become out of date with the actual output of the tool.
This can be quite confusing, as it makes it unclear which features the tool has.
Update the README.rst content and make sure it stays up to date via a pytest test case.
This is an alternative to #64. Instead of adding a custom Actions workflow for a special check, integrate it as a test into the pytest testsuite. This also gives us the diff output through assertions (see https://github.com/jluebbe/usbsdmux/actions/runs/7288823489/job/19862144881#step:4:84 as an example).
> add test that checks README.rst against usbsdmux -h output

- README.rst
`.. raw::`-directives are not allowed on pypi. Let's just switch to using the image-directive to generate basically the same output.
I am aware that the `:align:` directive does not work in the rendered file (at the moment). This seems to be a consequence of how Github handles external images: For images that are part of the repository `:align:` works, but pointing to something outside the repository doesn't.
> README: Replace RAW-HTML with image

- Makefile
- REQUIREMENTS.qa.txt
- tests/test_cli.py
During development we wanted to run the tests locally. Since we only have a few tests we decided to add them to `make qa`.
This also adds a new check to `test_help_in_readme()` that fails when the output in the README is zero lines long. This can happen when indentation is wrong :-) 
(And while we are on it add some meaningful messages to the asserts.)
To be merged after #68 .
> Testing: Allow to run tests locally and make README-test more verbose

- README.rst
- tests/test_cli.py
Hi,
I've spent some time with the README recently and found a few things that I would like to see changed.
Since changes in prose like a README are always a bit subjective I am of curse open for discussion. Feel free to point out changes you do not like.
> README: fixes, tweaks and re-organisation

- .github/workflows/check-and-build.yaml
- Makefile
- REQUIREMENTS.qa.txt
- fastentrypoints.py
- pyproject.toml
- setup.py
- tests/test_cli.py
- tests/test_sd_regs.py
- usbsdmux/__main__.py
- usbsdmux/ctypehelper.py
- usbsdmux/i2c_gpio.py
- usbsdmux/mqtthelper.py
- usbsdmux/sd_regs.py
- usbsdmux/usb2642eeprom.py
- usbsdmux/usbsdmux.py
The main benefit of using `ruff` for us is that its rules are automatically consistent between the formatter and linter, while `black` and `flake8` are often caught fighting about the correct formatting and need fine tuned configurations to prevent that.
This aligns with changes we have previously made to  [usbmuxctl](https://github.com/linux-automation/usbmuxctl) and [lxa-iobus](https://github.com/linux-automation/lxa-iobus).
TODO before merging:
> QA: Use ruff instead of black + flake8 for formatting and linting

- REQUIREMENTS.qa.txt
- usbsdmux/mqtthelper.py
It turns out that some points were missed when doing the `pyproject.toml` migration in #76.
Nothing mayor so far, but a few inconsistencies nevertheless.
This PR fixes two of them. Time will tell if there are even more.
> pyproject.toml: fix fallout from the migration

- usbsdmux/usbsdmux.py
This change fixes the mapping between the GPIO numbers (as written on the device) and the IOs of the I2C port-expander.
This mismatch was present since support for the FAST was added in ab421354c2bfeecd634a8ec54fb27e6a24c8c82a.
It seems the swapping of the pins in the schematic has been overlooked (see https://github.com/linux-automation/usbsdmux/issues/83 for that particular part of the schematic) during tool development. Additionally early prototypes were missing the GPIO numbers in silkscreen - masking this problem.
With this change we will break the pin assignment for all users of releases up to 24.01.1. Thus this must be added to the release notes.
I have tested these changes on a series production device. The pin definition is now correct.
> usb-sd-mux/FAST: Fix GPIO number-to-pin definition

- usbsdmux/sd_regs.py
It looks like `ruff` has learned a new trick, making the CI pipeline in #88 fail, even though it did not touch the python code at all.
This PR should fix that.
The primary goal of this commit is fixing the following `ruff` linting error:
usbsdmux/sd_regs.py:39:50: UP031 Use format specifiers instead of percent format
|
37 |             text.append(f"  {f['field']}")
38 |         raw = f["raw"]
39 |         text.append(f"    raw: 0b{format(raw[0], '0%db' % raw[1])} == 0x{raw[0]:0x} == {int(raw[0])}")
|                                                  ^^^^^^ UP031
40 |         if "enum" in f:
41 |             text.append(f"    enum: {f['enum']} {f.get('unit', '')}".rstrip())
|
= help: Replace with format specifiers
While at it I had a hard time understanding what the offending code does, so …
> usbsdmux: sd_regs: Fix ruff error regarding the use of percent formatting

- .github/workflows/check-and-publish.yaml
Running checks on a schedule makes sense for our `ruff` lints and our `codespell` spell checks, because these tools learn new lints/typo fixes every then and now.
Without periodic job runs these new lints/typo fixes will only surface when jobs for the next pull request fail for unrelated reasons.
The execution time of the scheduled job is chosen somewhat arbitrarily.
While at it also enable workflow_dispatch as a trigger, which can be used to run the jobs manually.
> CI: run checks on a schedule and allow workflow_dispatch

- contrib/udev/99-usbsdmux.rules
We never got around to figuring out why the `sg` module is auto-loaded on some systems/distributions (e.g. Debian) but not on others (e.g. Arch). We have since used workarounds like adding `sg` to `/etc/modules`.
Instead just use udev to load the module if a new USB-SD-Mux is connected, as suggested by @frosteyes in https://github.com/linux-automation/usbsdmux/issues/87.
I've tested the change on may Arch Linux System that would not automatically load the `sg` module before, but does with the updated udev rule. I've also checked if having an explicit `kmod load` in an (upstream) udev rule is uncommon:
```
$ cd /usr/lib/udev
rg kmod
rules.d/80-drivers.rules
5:ENV{MODALIAS}=="?*", RUN{builtin}+="kmod load"
6:SUBSYSTEM=="tifm", ENV{TIFM_CARD_TYPE}=="SD", RUN{builtin}+="kmod load tifm_sd" …
```
> contrib/udev: explicitly load the sg module in the udev rule

- .github/workflows/reuse.yaml
This updates the check to use version 3.3 of the spec.
> CI: update reuse-action to v5
